### ISSUE TITLE
qewd Installation Issue - ng-dbx module not found

### ISSUE THREAD

**Issue by DodgeDeBoulet** [robtweed/qewd-microservices-examples#1]
Just a note on the installation process ... On IRIS 2022.2 preview 4 I had to separately (re-)install mg-dbx before I could get qewd-monitor to start. The error reported was that the mg-dbx module could not be found:

```
*** uncaughtException in worker 66290 at Wed, 17 Aug 2022 11:44:52 GMT
Error: Cannot find module 'mg-dbx'
Require stack:
- /isc/i4h/qewd/node_modules/qewd-mg-dbx/lib/qewd-mg-dbx.js
- /isc/i4h/qewd/node_modules/qewd-mg-dbx/index.js
- /isc/i4h/qewd/node_modules/ewd-qoper8-dbx/lib/dbx.js
- /isc/i4h/qewd/node_modules/ewd-qoper8-dbx/index.js
- /isc/i4h/qewd/node_modules/qewd/lib/worker.js
- /isc/i4h/qewd/node_modules/qewd/lib/qewd.js
- /isc/i4h/qewd/node_modules/qewd/index.js
- /isc/i4h/qewd/node_modules/ewd-qoper8/lib/worker/proto/init.js
- /isc/i4h/qewd/node_modules/ewd-qoper8/lib/ewd-qoper8.js
- /isc/i4h/qewd/node_modules/ewd-qoper8/index.js
- /isc/i4h/qewd/node_modules/ewd-qoper8-worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at new db (/isc/i4h/qewd/node_modules/qewd-mg-dbx/lib/qewd-mg-dbx.js:63:14)
    at module.exports (/isc/i4h/qewd/node_modules/ewd-qoper8-dbx/lib/dbx.js:78:15)
    at workerProcess.<anonymous> (/isc/i4h/qewd/node_modules/qewd/lib/worker.js:79:38)
    at workerProcess.emit (events.js:314:20)
    at workerProcess.messageHandler (/isc/i4h/qewd/node_modules/ewd-qoper8/lib/worker/proto/messageHandler.js:45:10)
    at process.<anonymous> (/isc/i4h/qewd/node_modules/ewd-qoper8/lib/worker/proto/init.js:66:20)
*** worker 66290 is shutting down now ...
```

Still working my way through the tutorial. I'll report back if I find any other anomalies :)

**Comment by DodgeDeBoulet** [comment]
So ... I should have noted in my original post that I was doing all of this on Ubuntu 22.04 ARM64, running on a Raspberry Pi 4.

Although I managed to get mg-dbx installed as previously noted, the person editor would not load the 3 records I had populated in the Person table. I suspect this was because the **zmgsi_isc.ro** object had not been installed in %SYS. It took me a while to figure that out, with (quite possibly unnecessary) steps that involved updating to Node 18.7 (works fine) and cloning Chris Munt's mgsi repo to obtain the zmgsi_isc.ro routines for installation on IRIS.

Thanks for putting this all together, by the way. I'm not a js guy by any stretch, but I've found it mostly very easy to follow along and feel  like I have a good handle on what's going on.

And on a related note: If you have an IRIS authentication snippet that would replace or integrate with qewd-apps/demo/login/index.js, I'd love to see it.
